pimutils/vdirsyncer

- .travis.yml
- CONTRIBUTING.rst
- Makefile
- build.sh
Hopefully I'll be able to move more and more stuff from build.sh to standard
build tools.
> Add makefile

- docs/supported.rst
This is a bit of a shameless plug, but I *did* design todoman with vdirsyncer support in mind, and there doesn't seem to by anything else listed to cover these requirements. 😄
Thanks for vdirsyncer, BTW, it did make it possible for me to *finally* organize my list of todos.
> Mention todoman as a supported client.

- .travis.yml
- CHANGELOG.rst
- setup.py
- tests/storage/test_http.py
- vdirsyncer/storage/http.py
- vdirsyncer/utils/__init__.py
> Use FingerprintAdapter from req-toolbelt

- CHANGELOG.rst
- docs/ssl-tutorial.rst
- tests/storage/test_http.py
- vdirsyncer/cli/utils.py
- vdirsyncer/exceptions.py
- vdirsyncer/storage/base.py
- vdirsyncer/storage/dav.py
- vdirsyncer/storage/http.py
- vdirsyncer/storage/memory.py
- vdirsyncer/storage/singlefile.py
- vdirsyncer/sync.py
> Disallow verify=false

- vdirsyncer/storage/dav.py
> Skip empty items

- vdirsyncer/storage/dav.py
> Fix encoding bug in upload

- tests/storage/dav/test_main.py
- vdirsyncer/storage/dav.py
> Make XML parsing more tolerant re invalid chars

- tests/storage/dav/test_main.py
- tests/test_sync.py
- vdirsyncer/storage/dav.py
- vdirsyncer/storage/filesystem.py
- vdirsyncer/sync.py
- vdirsyncer/utils/__init__.py
- vdirsyncer/utils/compat.py
> Fix unicode URLs

- tests/storage/__init__.py
- vdirsyncer/storage/dav.py
- vdirsyncer/storage/filesystem.py
> Fix special chars once again

- .travis.yml
- tests/storage/__init__.py
This reverts commit 565ef2e96e724efe052b695790667ebc3a6b4f87.
> Revert "xfail owncloud, #255"

- tests/conftest.py
- tests/storage/__init__.py
- vdirsyncer/cli/__init__.py
- vdirsyncer/cli/tasks.py
- vdirsyncer/cli/utils.py
- vdirsyncer/storage/base.py
- vdirsyncer/storage/filesystem.py
- vdirsyncer/storage/singlefile.py
- vdirsyncer/sync.py
Fix #269 
This should make first sync on larger collections incredibly fast.
> Parallelize absolutely everything

- .travis.yml
- scripts/make_travisconf.py
- vdirsyncer/utils/compat.py
> Add davical tests to Travis

- .travis.yml
- Makefile
- scripts/make_travisconf.py
- vdirsyncer/storage/remotestorage.py
https://github.com/untitaker/mysteryshack
This is the first remoteStorage server to be tested in Travis.
I already started testing reStore (https://github.com/jcoglan/restore), but
stopped the experiments because the server is unmaintained.
> Test mysteryshack

- CHANGELOG.rst
- docs/keyring.rst
- setup.py
- tests/cli/test_fetchparams.py
- vdirsyncer/cli/fetchparams.py
> Remove keyring support

- docs/tutorial.rst
* docs/tutorial.rst (Installation): Add link to GNU Guix package.
> Mention GNU Guix package

- tests/conftest.py
- tests/storage/dav/__init__.py
- vdirsyncer/cli/__init__.py
> Warn when running under Python 2

- docs/when.rst
> Rewrite 'When' page

- CHANGELOG.rst
- config.example
- docs/config.rst
- docs/tutorial.rst
- tests/cli/test_config.py
- tests/cli/test_main.py
- vdirsyncer/cli/config.py
- vdirsyncer/cli/utils.py
> Remove the default of collections to autodiscovery

- tests/cli/test_main.py
- vdirsyncer/cli/config.py
- vdirsyncer/cli/utils.py
- vdirsyncer/exceptions.py
> Add prettier message when syncing inexistent pair

- tests/cli/test_utils.py
- vdirsyncer/cli/utils.py
> Fix coerce_native

- CHANGELOG.rst
- tests/test_metasync.py
- vdirsyncer/metasync.py
> metasync: Strip whitespace from values

- MANIFEST.in
- Makefile
- docs-requirements.txt
- docs/index.rst
- docs/packaging.rst
- setup.py
- test-requirements.txt
- tests/cli/test_main.py
- tests/conftest.py
> Add packaging guidelines

- Makefile
- tests/conftest.py
> Replace instances of envvar TRAVIS with CI

- tests/__init__.py
- tests/cli/test_repair.py
- tests/storage/__init__.py
- tests/test_metasync.py
- vdirsyncer/metasync.py
- vdirsyncer/storage/base.py
- vdirsyncer/storage/dav.py
- vdirsyncer/storage/filesystem.py
- vdirsyncer/storage/memory.py
- vdirsyncer/storage/remotestorage.py
This fixes #358 again, in a different way.
> Refactor metadata None values

- docs/supported.rst
- tests/storage/__init__.py
Ref #160
Ref https://github.com/fruux/sabre-dav/issues/422
> Remove old Baikal xfails

- tests/storage/__init__.py
> Remove owncloud xfails

- tests/utils/test_main.py
> Add tests for open_graphical_browser

- vdirsyncer/cli/__init__.py
- vdirsyncer/cli/fetchparams.py
- vdirsyncer/log.py
- vdirsyncer/metasync.py
- vdirsyncer/repair.py
- vdirsyncer/storage/dav.py
- vdirsyncer/storage/filesystem.py
- vdirsyncer/storage/remotestorage.py
- vdirsyncer/storage/singlefile.py
- vdirsyncer/sync.py
- vdirsyncer/utils/http.py
> Clean up logging usage

- .gitignore
- .gitmodules
- Makefile
- setup.cfg
> Add servers as submodules

- .travis.yml
- scripts/make_travisconf.py
- scripts/travis-install.sh
- tests/cli/test_main.py
- tests/storage/__init__.py
> Test against OS X (PR)

- CHANGELOG.rst
- docs/config.rst
- docs/supported.rst
- setup.py
- tests/utils/test_main.py
- vdirsyncer/cli/utils.py
- vdirsyncer/storage/dav.py
- vdirsyncer/storage/google.py
- vdirsyncer/storage/http.py
- vdirsyncer/utils/__init__.py
> Google contacts and calendar

- tests/cli/test_discover.py
- vdirsyncer/cli/utils.py
> Nicer output for unsupported discovery

- tests/cli/test_sync.py
- vdirsyncer/cli/utils.py
> CLI worker: Show how many tasks failed

- vdirsyncer/storage/google.py
> Py2: If file doesn't exist, IOError will be raised

- docs/config.rst
- docs/supported.rst
- vdirsyncer/storage/google.py
Change the documentation accordingly
Fix #407
> Remove default client ID for Google

- CHANGELOG.rst
- docs/config.rst
- tests/cli/test_config.py
- tests/cli/test_discover.py
- vdirsyncer/cli/config.py
- vdirsyncer/cli/utils.py
> Ability to sync differently named collections with each other

- tests/test_sync.py
See #432
These new tests fail for some obscure reason and I have no idea what's going on
at the moment.
> Hypothesis tests for sync

- MANIFEST.in
- contrib/vdirsyncer.plist
> Initial MacOS X launchd .plist file.

- docs/tutorial.rst
- tests/cli/test_discover.py
- tests/cli/test_sync.py
- vdirsyncer/cli/__init__.py
- vdirsyncer/cli/utils.py
> Make discovery explicit

- docs/tutorial.rst
> Add example for metadata sync

- CHANGELOG.rst
- tests/conftest.py
- vdirsyncer/cli/__init__.py
- vdirsyncer/cli/config.py
The error can be disabled with a config option.
See #219
> Show error for Python 2 users

- tests/storage/__init__.py
> Fix defective discovery test

- setup.py
- vdirsyncer/storage/google.py
> Fix race conditions in Google storage

- vdirsyncer/storage/google.py
noticed while working on #464 :)
> it has to be note:: otherweise sphinx won't render the paragraph at all

- .gitmodules
- .travis.yml
- scripts/make_travisconf.py
> Test nextcloud

- tests/cli/test_discover.py
- tests/cli/test_sync.py
- vdirsyncer/cli/tasks.py
- vdirsyncer/cli/utils.py
> Kill special codepath for `null`-collection

- .travis.yml
- scripts/make_travisconf.py
- scripts/travis-install.sh
The current behavior is annoying in combination with homu.io
Reverts #387
> Run all tests in PR

- tests/test_sync.py
- vdirsyncer/storage/dav.py
Thanks to @evert for pointing this out in the #sabredav IRC channel.
> DAV: Fix behavior when PUT doesn't return ETag

- CHANGELOG.rst
- tests/storage/test_http.py
- vdirsyncer/storage/http.py
> Make auth = basic the default again

- .travis.yml
- scripts/make_travisconf.py
- scripts/travis-install.sh
Reverts pimutils/vdirsyncer#475
DavICal tests fail in PRs because the environment variables are not available for security reasons. Maybe fix them? I don't know. See #481
> Revert "Run all tests in PR"

- .travis.yml
- CHANGELOG.rst
- docs/installation.rst
- scripts/make_travisconf.py
- tests/cli/test_fetchparams.py
- tests/cli/test_sync.py
- tests/cli/test_utils.py
- tests/conftest.py
- tests/storage/__init__.py
- tests/storage/servers/radicale/__init__.py
- tests/utils/test_main.py
- vdirsyncer/__init__.py
- vdirsyncer/cli/__init__.py
- vdirsyncer/cli/config.py
- vdirsyncer/cli/tasks.py
- vdirsyncer/cli/utils.py
- vdirsyncer/storage/base.py
- vdirsyncer/storage/dav.py
- vdirsyncer/storage/filesystem.py
- vdirsyncer/storage/google.py
- vdirsyncer/storage/http.py
- vdirsyncer/storage/remotestorage.py
- vdirsyncer/storage/singlefile.py
- vdirsyncer/sync.py
- vdirsyncer/utils/__init__.py
- vdirsyncer/utils/compat.py
- vdirsyncer/utils/vobject.py
> Remove Python 2 support

- .codecov.yml
This will fix the status for sure. The comment may be fixed as well since the yaml is now valid
> CC https://github.com/codecov/support/issues/162#issuecomment-250472579
> fix yaml syntax

- vdirsyncer/storage/dav.py
> Ability to pass homeset-url for DAV storage

- CHANGELOG.rst
- docs/config.rst
- tests/cli/test_sync.py
- tests/test_sync.py
- vdirsyncer/cli/config.py
- vdirsyncer/cli/tasks.py
- vdirsyncer/cli/utils.py
- vdirsyncer/sync.py
> Partial sync

- vdirsyncer/cli/config.py
- vdirsyncer/cli/utils.py
Remove conditional imports left over from python2/3 support.
> Remove obsolete conditional imports

- .travis.yml
- Makefile
- scripts/make_travisconf.py
> Don't run tests multiple times

- docs/supported.rst
Adding some documentation around what users can do if they encounter duplicate events using DavMail.
> Adding tip about Microsoft's Remove-DuplicateAppointments.ps1

- .travis.yml
- scripts/make_travisconf.py
- scripts/travis-install.sh
> Enable PyPy3

- CHANGELOG.rst
- vdirsyncer/storage/dav.py
- vdirsyncer/storage/google.py
> Work around Google Contacts discovery bug

- .travis.yml
- AUTHORS.rst
- scripts/make_travisconf.py
- tests/storage/__init__.py
- tests/storage/conftest.py
- tests/storage/dav/__init__.py
- tests/storage/servers/fastmail/__init__.py
- tests/storage/servers/icloud/__init__.py
> Add fastmail testserver

- tests/storage/test_filesystem.py
- vdirsyncer/storage/filesystem.py
> Ignore fs collections that have subfolders

- docs/config.rst
- vdirsyncer/storage/google.py
> Document that gcal doesn't support VTODO

- vdirsyncer/storage/dav.py
> Add trailing slash on discovery

- CHANGELOG.rst
- tests/unit/test_sync.py
- vdirsyncer/cli/tasks.py
- vdirsyncer/cli/utils.py
- vdirsyncer/sync.py
> Switch to sqlite for sync status

- tests/system/cli/test_sync.py
> Disable OS X in Travis

- docs/tutorial.rst
Fix #619
@unkraut check this out.
> More discovery docs

- docs/tutorial.rst
> More quoting

- docs/keyring.rst
Add minimal explanation for using external password manger named `pass`
to automatically safely and fetch the password.
> Add more instructions regarding `docs/keyring.rst`.

- vdirsyncer/http.py
> Better useragent

- CHANGELOG.rst
- vdirsyncer/storage/singlefile.py
- vdirsyncer/utils.py
> Use inode number in addition to mtime

- tests/conftest.py
This makes it a bit easier to manually run individual tests.
> Set defaults for CI and DETERMINISTIC_TESTS.

- .travis.yml
- scripts/make_travisconf.py
See https://github.com/travis-ci/travis-ci/issues/2778#issuecomment-329968553
See https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#Conditional-Jobs
> Use travis' new conditional branches

- .gitignore
- docs/installation.rst
- rust/.gitignore
- rust/Cargo.toml
- rust/build.rs
- rust/src/lib.rs
- scripts/dpkg.Dockerfile
- scripts/travis-install.sh
- setup.cfg
- setup.py
- tests/__init__.py
- tests/storage/__init__.py
- tests/storage/dav/test_caldav.py
- tests/storage/test_filesystem.py
- tests/system/cli/test_repair.py
- tests/system/cli/test_sync.py
- tests/unit/sync/test_sync.py
- tests/unit/test_repair.py
- tests/unit/utils/test_vobject.py
- vdirsyncer/exceptions.py
- vdirsyncer/native.py
- vdirsyncer/vobject.py
> Use rust-vobject

- docs/tutorials/claws-mail.rst
> fixed typo

- tests/unit/test_exceptions.py
- vdirsyncer/cli/utils.py
Past tense of "occur" is "occurred". 
https://www.wordnik.com/words/occurred
> Little spelling fix

- .gitignore
- .travis.yml
- CHANGELOG.rst
- Makefile
- scripts/make_travisconf.py
- setup.cfg
- tests/storage/__init__.py
> Make a maintenance release of vdirsyncer

- .circleci/config.yml
> Add iCloud to circleci

- .circleci/config.yml
- tests/storage/servers/davical/__init__.py
> Reenable davical

- docs/tutorials/baikal.rst
> baikal-server.com does not work anymore

- docs/installation.rst
adding closing quote to virtualenv alias
> Update installation.rst - add closing quote to virtualenv alias

- docs/installation.rst
pipsi page says, it is discontinued. Replacing with pipx
> Replace pipsi with pipx

- docs/contact.rst
@pimutils/core Any of you know where that website is hosted?
> Replace Freenode with Libera.Chat

- .gitignore
- tests/storage/__init__.py
Some polishing to make tests faster.
> Faster tests

- contrib/conflict_resolution/resolve_interactively.py
Asks the user when two iCalender objects conflict during a sync,
which one to take. Documentation within the file itself.
> Add contrib script to resolve conflicts

- AUTHORS.rst
- contrib/vdirsyncer.service
Fixes https://github.com/pimutils/vdirsyncer/issues/998
> Make systemd service restart only once on failure

- vdirsyncer/cli/discover.py
Fixes: https://github.com/pimutils/vdirsyncer/issues/994
> Google Contacts discover fix

- vdirsyncer/http.py
Fixes: https://github.com/pimutils/vdirsyncer/issues/1033
> Fix crash when using auth certs

- docs/config.rst
Even though it's unclear whether this might be fixed in the future, I guess a note in the docs would be beneficial as long as it isn't.
Thanks in advance for your feedback!
Reference: #814
> Document caveats of Google contacts storage

- docs/installation.rst
> Fix link to GNU Guix package in documentation

- vdirsyncer/cli/__init__.py
- vdirsyncer/cli/config.py
- vdirsyncer/cli/tasks.py
- vdirsyncer/cli/utils.py
- vdirsyncer/storage/dav.py
- vdirsyncer/sync/__init__.py
I was browsing the commit history since I notice there was a new release, and I've seen there was a commit adding some type annotation, so I try to add some typing myself.
I mainly added types in the `cli/config.py` file and I run `ruff` which fix a couple of things.
I hope you find the PR useful, otherwise I won't be offended if you close it.
> Add typing annotations

- docs/installation.rst
Package url for Arch Linux has been changed
> Fix broken Arch Linux package link

- docs/keyring.rst
tested with vdirsyncer 0.19.2 on archlinux
> docs: add instructions to get pw from environment variable

- docs/contact.rst
Cc: @untitaker 
Fixes: https://github.com/pimutils/vdirsyncer/issues/1104
> Remove broken contact link

- docs/config.rst
- vdirsyncer/storage/filesystem.py
closes https://github.com/pimutils/vdirsyncer/issues/1107
> add `pre_deletion_hook`

- AUTHORS.rst
- CHANGELOG.rst
- README.rst
Hey @WhyNotHugo :)
I updated the description for the Docker build, as you mentioned in the previous PR #932 .
So everyone should know, that my Docker container is not an official one, but maintained by me.
Repository:
[Vdirsyncer DOCKERIZED](https://github.com/Bleala/Vdirsyncer-DOCKERIZED)
Old PR:
#932 
Would be nice, if you would merge my PR now. :)
Greetings
> Added Docker Enviroment

- docs/tutorials/todoman.rst
stumbled upon this while setting up todoman
> docs: update config info on todoman tutorial

- pyproject.toml
Fixes: https://github.com/pimutils/vdirsyncer/issues/1111
> Bump constraint for aiostream
