- docs/ssl-tutorial.rst
- vdirsyncer/storage/dav.py
- vdirsyncer/storage/http.py
---
Tested with Davical+nginx locally.
> ssl: support client certificates

- tests/storage/__init__.py
- tests/storage/dav/servers/radicale/__init__.py
- tests/storage/test_filesystem.py
- vdirsyncer/storage/dav.py
- vdirsyncer/storage/filesystem.py
- vdirsyncer/utils/__init__.py
The set of safe characters was inspired by the set of safe characters in
URLs.
Fixes #229
> Create always safe hrefs

- vdirsyncer/storage/dav.py
The exception message contained `{!r}` but it was never fed to `format()`
> Repair message for exception

- .travis.yml
- Makefile
- docs/config.rst
- setup.py
- tests/storage/test_remotestorage.py
- vdirsyncer/cli/utils.py
- vdirsyncer/storage/remotestorage.py
> Remotestorage

- setup.py
See https://github.com/travis-ci/travis-ci/issues/5130
Meta: https://github.com/untitaker/vdirsyncer/issues/298
> Use older lxml because of Travis

- docs/tutorial.rst
(the example from the doc crashes on setting validation)
> Fix typo on collection discovery doc

- setup.py
This allows using `python setup.py requirements` to print minimum requirement versions.
Use `python setup.py --quiet requirements` to avoid setuptools printing "running requirements", which we don't want to see when scripting.
**NOTE**: this PR intends to merge into `packaging-guidelines`, and *not* into `master`.
> Implement command to print minimal requirements

- test-requirements.txt
It is only required by ownCloud and Baikal testservers.
> Remove pytest-xprocess from test requirements

- CHANGELOG.rst
- tests/utils/test_main.py
List may be empty if running in minimal environment.
> Fix broken test for webbrowser internals

- CHANGELOG.rst
- tests/storage/__init__.py
- vdirsyncer/utils/vobject.py
Previously we moved each VEVENT into its own Item, now we group by UID,
if one exists.
> Split recurring events properly

- docs/contributing.rst
- docs/index.rst
> Split table of contents into three categories

- vdirsyncer/storage/google.py
- vdirsyncer/utils/__init__.py
- the tilde wouldn't be expanded to $HOME for token_file value, causing
a crash
- due to wrong type signatures, vdirsyncer's storage init code would
guess that the instance_name parameter was not allowed, and that that
lead to the crash
> Bugfixes for Google storage

- vdirsyncer/utils/__init__.py
If there are no defaults, spec.args would be sliced like
`spec.args[1:0]` which always produces an empty slice.
> Fix bug in storage init errorhandler

- vdirsyncer/cli/__init__.py
- vdirsyncer/cli/utils.py
- The new `--list` option for `vdirsyncer discover`, enabled by default,
makes vdirsyncer list all collections before saving the configuration.
It is not enabled when vdirsyncer tries to discover when invoked via
`vdirsyncer sync`. Fix #424
- There are no duplicate collections anymore. Fix #419.
- `vdirsyncer discover` is running with one worker by default now, to
avoid broken output. See also #404.
> Refactor UX of discovery

- vdirsyncer/storage/dav.py
Currently, `find_dav` only resolves a single redirect. When using Baïkal behind a proxy with HTTPS, this becomes an issue:
1. dav.example.com/.well-known/caldav (Apache rewrite to http)
2. dav.example.com/dav.php (http)
3. dav.example.com/dav.php (https)
The Apache configuration is provided by Baïkal, hence it is also possible to fix it server-side:
-RewriteRule /.well-known/carddav /dav.php [R,L]
+RewriteRule /.well-known/carddav https://dav.example.com/dav.php [R,L]
-RewriteRule /.well-known/caldav /dav.php [R,L]
+RewriteRule /.well-known/caldav https://dav.example.com/dav.php [R,L]
This commit follows the well-known URI up to 5 times and returns the (hopefully) correctly resolved url.
> fully resolve well-known URI

- tests/storage/test_singlefile.py
- vdirsyncer/storage/singlefile.py
> Introduce collections for singlefile storage

- tests/test_sync.py
- vdirsyncer/storage/dav.py
The implementation of #476 is problematic as it returns None.
`vdirsyncer.sync` has internal assertions that this is a string, which
is why we get a crash like this:
error: Unknown error occured for cal/markus@unterwaditzer.net:
error: Use `-vdebug` to see the full traceback.
debug:   File "/home/untitaker/projects/vdirsyncer/vdirsyncer/cli/tasks.py", line 66, in sync_collection
debug:     force_delete=force_delete
debug:   File "/home/untitaker/projects/vdirsyncer/vdirsyncer/sync.py", line 228, in sync
debug:     action(a_info, b_info, conflict_resolution)
debug:   File "/home/untitaker/projects/vdirsyncer/vdirsyncer/sync.py", line 276, in inner
debug:     assert isinstance(dest_etag, (bytes, text_type))
Discovered in #467
> DAV: Don't violate Storage API

- tests/test_sync.py
- vdirsyncer/storage/base.py
- vdirsyncer/sync.py
- Using `info.idents` as new status, this saves a few operations where
no storage actions have to be taken, but the status has to be updated.
- Rename StorageSyncer to _StorageInfo and make it a private API again.
- Ability to pass custom functions for conflict resolution. This part is
a preparation for #127.
> Refactor of status handling in sync

- vdirsyncer/storage/dav.py
- vdirsyncer/storage/google.py
According to RFC6764 URLs should be "/.well-known/caldav" and
"/.well-known/caldav".
Tested with Baïkal, but redirect for .well-known-URIs defined in nginx config so it is not Baïkal-specific.
May be `https://www.googleapis.com/.well-known/carddav/` should also be changed to `https://www.googleapis.com/.well-known/carddav`. See: https://developers.google.com/google-apps/carddav/ But I don't use vdirsyncer with google and can't test this change.
> Strip trailing slash from .well-known-URIs to fix autodiscovery

- docs/when.rst
Resulting in lintian complain:
I: vdirsyncer: spelling-error-in-manpage usr/share/man/man1/vdirsyncer.1.gz errorneous erroneous
> Fix spelling error in docs

- tests/storage/__init__.py
- tests/storage/dav/test_caldav.py
- tests/test_sync.py
- vdirsyncer/storage/base.py
- vdirsyncer/storage/dav.py
- vdirsyncer/sync.py
nextCloud now returns no etag on upload, which is why we're forced to
adapt the tests accordingly. So now we need to specify a fixed value for
"no etag returned" such that the tests can act accordingly. We also need
to test that the sync algorithm works properly with None.
> Return back to None as non-ETag

- .travis.yml
- scripts/make_travisconf.py
- tests/storage/__init__.py
- tests/storage/dav/test_caldav.py
- tests/storage/servers/icloud/__init__.py
- vdirsyncer/storage/base.py
- vdirsyncer/utils/vobject.py
> Test iCloud

- config.example
Seems like this one is missing quotation (and I was unable to get vdirsyncer working without it).
> config.example: Status path needs to be quoted

- CHANGELOG.rst
- docs/ssl-tutorial.rst
- docs/tutorials/claws-mail.rst
- vdirsyncer/storage/base.py
- vdirsyncer/sync.py
- vdirsyncer/vobject.py
I installed mwic, so you don't have to.
`unperformant` doesn't seem to be an often used english word either and
`addressbook` is probably `address book`.
> Fixed some typos.

- CHANGELOG.rst
- vdirsyncer/http.py
- vdirsyncer/storage/dav.py
- vdirsyncer/storage/google.py
>  	Make discovery more RFC-conformant

- docs/tutorial.rst
Without the quotes the app doesn't start, throwing: 
```
critical: Error during reading config /home/kuba/.vdirsyncer/config: Section "general": Section "general", option "status_path": Expecting value: line 1 column 1 (char 0)
```
> Add quotes to the suggested config

- .travis.yml
- CHANGELOG.rst
- docs/supported.rst
- scripts/make_travisconf.py
- tests/storage/servers/xandikos/__init__.py
- tests/storage/servers/xandikos/install.sh
> Add xandikos to CI

- vdirsyncer/sync.py
This is in preparation for #546. Instead of using a dictionary, we define a class that exposes a limited interface to that dictionary. Instead of copying the dictionary into a different format, we define a proxy class.
> Abstract status into own class

- tests/unit/test_sync.py
- vdirsyncer/sync.py
Another preparation for #546
This loads the legacy JSON format into a in-memory sqlite db, does some
operations there and converts it back into JSON at the end. That's not the end
goal, but makes testing easier since we don't have to modify any tests. Later
we can then modify `sync` to finally accept a sqlite db object and do the
necessary modifications in `vdirsyncer.cli`.
Right now there are two correctness bugs left though.
> Use sqlite for sync internally

- docs/tutorial.rst
avoids a warning on use
Closes #628
> Properly quote "b wins"

- CHANGELOG.rst
- contrib/vdirsyncer.service
- contrib/vdirsyncer.timer
- docs/packaging.rst
- docs/tutorials/index.rst
- docs/tutorials/systemd-timer.rst
Include a `systemd.timer` file (the interval can be overridden, as mentioned in the docs).  
TBH, I'd suggest downstream packagers of systemd-based distributions include these files on installation
(activation needs to be done manually anyway).
> Add systemd.timer files and a relevant tutorial

- .travis.yml
- CHANGELOG.rst
- Makefile
- docs/installation.rst
- scripts/make_travisconf.py
- setup.py
- tests/unit/sync/test_status.py
- vdirsyncer/__init__.py
Hypothesis dropped Python 3.3 support and apparently it's EOL too.
> Remove Python 3.3 support

- docs/installation.rst
There's now an official Arch package in the [community] repositories.
Updated the docs to reflect this.
> There's now an official Arch package

- Makefile
- rust/.gitignore
- rust/Cargo.lock
- rust/Cargo.toml
- rust/build.rs
- rust/src/item.rs
- rust/src/lib.rs
- rust/src/storage/mod.rs
- rust/src/storage/singlefile.rs
- scripts/circleci-install.sh
- setup.py
- tests/storage/__init__.py
- tests/system/cli/test_sync.py
- tests/unit/utils/test_vobject.py
- vdirsyncer/cli/utils.py
- vdirsyncer/native.py
- vdirsyncer/storage/_rust.py
- vdirsyncer/storage/base.py
- vdirsyncer/storage/etesync.py
- vdirsyncer/storage/singlefile.py
- vdirsyncer/sync/__init__.py
- vdirsyncer/vobject.py
* Fix #683: We will now sanitize line endings if the item is otherwise valid
(if the item cannot be parsed we will not touch the line endings)
* Fix #578: We already emitted a warning in master.
* Works towards #375: We use rust-vobject for everything but HTTP storage
> Singlefile storage in rust

- .pre-commit-config.yaml
- .travis.yml
- CHANGELOG.rst
- Makefile
- scripts/make_travisconf.py
- setup.py
As soon as this turns green, I'll make a 0.16.8 release, which will be the last to support Python 3.5 and 3.6.
At that point, support for those two pythons will be dropped. They no longer receive bugfix support upstream anyway, so anyone wanting _any_ for of bugfixing, should upgrade to an upstream supported Python.
> Support Python 3.7 and 3.8

- contrib/vdirsyncer.service
Sometimes while doing a suspend/resume cycle vdirsyncer can hang in the
middle of sync, and it never bails out afterwards.
Implement a systemd service change that works around this:
* use `simple` (a default) type for `RuntimeMaxSec` to be effective
* actually set `RuntimeMaxSec` to 30 seconds
* trigger service restart on failure
Signed-off-by: Oleksandr Natalenko <oleksandr@natalenko.name>
> contrib/systemd: implement service timeout

- setup.py
Previous version broke with recent `click` updates.
See https://github.com/click-contrib/click-threading/pull/5
> Update click-threading to 0.5.0

- docs/config.rst
- tests/storage/test_filesystem.py
- vdirsyncer/storage/filesystem.py
* add parameter `#fileignoreext = ".tmp"` to storage/filesystem code, tests and docs.
* add hint to docs that vdir compatibility is only given with setting `fileext` properly
resolves #881
> Implement more flexibility for storage/filesystem

- vdirsyncer/cli/fetchparams.py
- vdirsyncer/utils.py
The first use exhausted it, so the second iteration was empty.
Also some typing hints for the affected code.
> Fix double-use of a generator

- CHANGELOG.rst
- tests/system/cli/test_discover.py
- vdirsyncer/cli/__init__.py
This is intended to be used by external tools and integrations (such as daemons which trigger `vdirsyncer` when there's a change in a collection).
> Add a command to print the current config

- .builds/archlinux.yaml
- CHANGELOG.rst
- test-requirements.txt
- tests/system/conftest.py
- tests/system/utils/test_main.py
Had to drop pytest-localserver, since it's broken and upstream is gone.
Fixes #902
> Fix SSL tests failing due to old weak MDs

- .builds/tests-release.yaml
- tests/storage/servers/fastmail/__init__.py
Run our test suite using Fastmail as a backed as part of CI again.
This was long ago set up for Travis, had broken at some point, and Travis was never fixed. Some tests are still being omitted due to some quirks in Fastmail (see #824).
Since `secrets` for Fastmail are required to run this, these will only run for branches of `pimutils/vdirsyncer`, and not for external PRs.
> Run Fastmail on CI again

- docs/tutorials/index.rst
The previous one is 404, and that domain redirects to some random website.
This seems to be unmaintained though, see the [xfce forums](https://forum.xfce.org/viewtopic.php?id=14898) for more details.
> Update link for orage

- .codecov.yml
- Makefile
We submit separate coverage reports for each group of tests, but codecov
doesn't give us proper tooling to analyse each one separately. When
there's a percentage drop in one, there's no way to pinpoint where -- at
least not without running locally and inspecting results separately.
Treat all coverage as one. Analysis of coverage for each group of tests
can be done offline and manually, but there's little value in keeping it
in codecov.
Should also help us transition a more simplified CI design (e.g.:
running all tests together rather than in groups).
> Simplify coverage submission

- vdirsyncer/cli/__init__.py
Not sure how I missed such an obvious one.
Speeds `sync` up by around 50% on my usual setups.
> Sync pairs asynchronously

- tests/storage/__init__.py
- tests/unit/test_metasync.py
- vdirsyncer/metasync.py
- vdirsyncer/storage/base.py
- vdirsyncer/storage/dav.py
- vdirsyncer/storage/filesystem.py
- vdirsyncer/storage/memory.py
This is #871 rebased onto the current `master`.
Closes #871
> metasync: use None as no-value and delete missing values on syncing

- .gitlab-ci.yml
- vdirsyncer/http.py
Still supporting it, so best to have running tests to make sure we don't break it (again).
Run these on a synthetic (dockerised) environment, since no distribution seems to currently ship this version.
> Run tests CI python 3.7

- AUTHORS.rst
- CHANGELOG.rst
- docs/keyring.rst
- tests/system/cli/test_fetchparams.py
- vdirsyncer/cli/fetchparams.py
Adds a new strategy, `shell`, to config fetch parameters. The syntax is nearly identical to the `command` strategy, except that the arguments are run using the `shell=True` subprocess option.
The rationale for this addition is that the output of some password managers (including `pass`) may require piping through additional commands. For example if a `pass` password file is structured as suggested in the documentation:
```
my-secret-password
URL: www.example.com
Username: myuser
```
Then to retrieve only the password, we need to filter the output, for example: `pass my-password | head -n1`
This could be handled on the user side by creating wrapper scripts, but those complicate the use of `vdirsyncer`. Many other tools commonly used in this space (isync, mutt, msmtp, etc.) support password …
> Add shell strategy to fetch params

- vdirsyncer/storage/google.py
- vdirsyncer/storage/google_helpers.py
Google Calendar has disabled the oob method for new credentials (see
https://developers.google.com/identity/protocols/oauth2/native-app), so
new users cannot currently use Google Calendar. Fix this by switching to
a loopback redirect_uri flow instead.
This is completely secure - Javascript on the OAuth2 authentication page
opened by the workflow makes a single GET request to a server listening
only on 127.0.0.1. Once the authentication page makes the GET request,
the local web server is not needed anymore and is immediately shut down.
Fix #975
> gcal: replace oob OAuth2 with local server redirect

- docs/installation.rst
I corrected the python source package for Ubuntu to be `python3`, and removed the pip `--user` option, since this is the default now: 
```
$ pip list -v | grep "vdirsyncer"
vdirsyncer              0.19.0               /home/USER/.local/lib/python3.8/site-packages pip 
```
> Corrected installation steps for Ubuntu and pip

- docs/installation.rst
I maintain the build script for Slackware on the slackbuilds.org repo (endorsed by Slackware).
> Add Slackware as build-able version

- vdirsyncer/storage/dav.py
- vdirsyncer/storage/http.py
I don't know why it wasn't enabled, but here it is.
> Enable environment variables for HTTP proxy

- vdirsyncer/storage/singlefile.py
For single file storage we wrap the logic of get_multi with the at_once context manager so that `self.list()` (which is called by `self.get()`) actually caches the items rather than re-computing them at every call.
This should largely mitigate the performance issue describe at https://github.com/pimutils/vdirsyncer/issues/818 . The issue discussion also contains more background about this patch.
> Prevent single file storage from performing unnecessary N^2 loop

- .builds/tests-minimal.yml
- .builds/tests-pypi.yml
Pip now refuses to tamper with the system python installation.
> ci: use virtualenvs for jobs that use pip

- CHANGELOG.rst
- vdirsyncer/cli/discover.py
- vdirsyncer/cli/tasks.py
Fixes error: `DAVSession.__init__() missing 1 required keyword-only argument: 'connector'` (#1019).
Reuses the existing logic in `DiscoverResult` to determine if the storage requires a `connector` arg.
Please let me know if there are any tests that I can extend without too much effort :)
> fix(repair_collection): use DiscoverResult logic to discover collection (#1019)

- AUTHORS.rst
- CHANGELOG.rst
- tests/unit/utils/test_vobject.py
- vdirsyncer/vobject.py
Raise an error when parsing a vobject that has mismatched `BEGIN` and `END` lines (e.g., `BEGIN:FOO` followed by `END:BAR`) or missing `END` lines (e.g., `BEGIN:FOO` with no subsequent `END:FOO`).
Fixes #1102.
> Require matching BEGIN and END lines in vobjects

- setup.py
- vdirsyncer/cli/__init__.py
This fixes pylint W0621: Redefining name 'main' from outer scope (line 68) (redefined-outer-name)
> fix pylint W0621: Redefining name 'main' from outer scope (line 68) (redefined-outer-name)

- setup.py
- tests/storage/test_http.py
- vdirsyncer/http.py
This PR makes the following changes:
- Re-implements digest auth by wrapping requests's `HTTPDigestAuth` and using it with aiohttp;
- Removes `requests_toolbelt` since it is no longer used;
- Shows a helpful (critial) error for `guess` auth to indicate that it is not supported;
- Updates the test for geuss auth to reflect its status.
Things to consider:
- The wrapper accesses an internal instance variable of `HTTPDigestAuth`, so it might be a good idea to pin requests to a specific version.
I can personally confirm that both basic and digest auth appear to work with a local baikal server, but more testing may be needed.
> Implement digest auth

- CHANGELOG.rst
- docs/config.rst
- vdirsyncer/storage/http.py
This allows users to process fetched items through a filter command,
to fix malformed webcal items as they are imported.
In my case, my provider adds the export time to the description and
random sequence numbers to all events. This caused the whole collection
to be invalidated and propagated at each sync. I use the filter to
remove those, canonicalising the items.
> storage/http: add support for `filter_hook`

- vdirsyncer/vobject.py
Hypothesis found the following example:
```
tests/unit/utils/test_vobject.py:335: in add_prop
assert c[key] == value
E   AssertionError: assert '0' == '1'
E
E     - 1
E     + 0
E   Falsifying example:
E   state = VobjectMachine()
E   unparsed_0 = state.get_unparsed_lines(encoded=False, joined=False)
E   parsed_0 = state.parse(unparsed=unparsed_0)
E   state.add_prop_raw(c=parsed_0, key='0', params=[], value='0')
E   state.add_prop_raw(c=parsed_0, key='0', params=[], value='0')
E   state.add_prop(c=parsed_0, key='0', value='1')
E   state.teardown()
```
After the two `add_prop_raw` calls, `c.props` is `["0;:0", "0;:0", "FOO:YES"]`.  `_Component.__delitem__` then fails to effectively delete the previous key: it deletes the first `"0;:0"` item, but then checks for continuation lines following …
> Fix _Component.__delitem__ with adjacent identical keys

- .builds/archlinux-py313.yml
The dependency was dropped in 89a01631facebc2724cace261fa2b6954dff3aa9
> Remove python-requests-toolbelt from Arch Linux build
